import argparse
import json
import dspy
import os
from agent.graph_hybrid import app
from rich.console import Console
from rich.progress import track

console = Console()

def main():
    parser = argparse.ArgumentParser(description="Retail Analytics Copilot")
    parser.add_argument("--batch", required=True, help="Input JSONL file")
    parser.add_argument("--out", required=True, help="Output JSONL file")
    args = parser.parse_args()

    # Configure DSPy with increased timeout for local CPU inference
    lm = dspy.OllamaLocal(
        model="phi3.5:3.8b-mini-instruct-q4_K_M",
        timeout_s=600  # 10 minutes per LLM call
    )
    dspy.settings.configure(lm=lm)

    # Load questions
    questions = []
    with open(args.batch, "r") as f:
        for line in f:
            if line.strip():
                questions.append(json.loads(line))

    results = []
    
    for i, q in enumerate(questions):
        print(f"Processing question {i+1}/{len(questions)}: {q['id']}")
        try:
            initial_state = {
                "question": q["question"],
                "format_hint": q["format_hint"],
                "repair_count": 0
            }
            
            # Run graph
            # config = {"configurable": {"thread_id": str(q["id"])}}
            final_state = app.invoke(initial_state)
            
            output = {
                "id": q["id"],
                "final_answer": final_state.get("final_answer"),
                "sql": final_state.get("sql_query", ""),
                "confidence": final_state.get("confidence", 0.0),
                "explanation": "Generated by Retail Analytics Copilot",
                "citations": final_state.get("citations", [])
            }
            results.append(output)
            
            # Write incrementally
            with open(args.out, "a") as f:
                f.write(json.dumps(output) + "\n")
            
        except Exception as e:
            console.print(f"[red]Error processing {q['id']}: {e}[/red]")
            error_output = {
                "id": q["id"],
                "final_answer": None,
                "sql": "",
                "confidence": 0.0,
                "explanation": f"Error: {str(e)}",
                "citations": []
            }
            results.append(error_output)
            with open(args.out, "a") as f:
                f.write(json.dumps(error_output) + "\n")

    console.print(f"[green]Done! Results written to {args.out}[/green]")

if __name__ == "__main__":
    main()
